services:
  web:
    restart: always
    build:
      context: ./webserver
      target: development
    container_name: "web_market"
    command: ["npm", "run", "dev"]
    working_dir: /usr/src/app
    tty: true
    volumes:
      - ./webserver/app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
  kafka:
    build:
      "./dataanalysis/kafka"
    container_name: "kafka_market"
    tty: true
  spark:
    build:
      "./dataanalysis/spark"
    container_name: "spark_market"
    tty: true
    ports:
      - 65432:65432

  # db:
  #   image: mysql:8.0.37-oracle
  #   container_name: "db_callcenter"
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: callcenterproject
  #     MYSQL_USER: pythonMySql1
  #     MYSQL_PASSWORD: pythonMySql1
  #     TZ: 'Asia/Tokyo'
  #   command: mysqld
  #   # volumes:
  #   #   - ./dbserver/conf/my.cnf:/etc/mysql/conf.d/my.cnf
  #   ports:
  #     - 3306:3306
  #   cap_add:
  #     - SYS_NICE
