services:
  web:
    restart: always
    build:
      context: ./webserver
      target: development
    container_name: "web_market"
    command: ["npm", "run", "dev"]
    working_dir: /usr/src/app
    tty: true
    volumes:
      - ./webserver/app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
  kafka:
    build:
      "./dataanalysis/kafka"
    container_name: "kafka_market"
    tty: true
    ports:
      - 9092:9092
  spark:
    build:
      "./dataanalysis/spark"
    container_name: "spark_market"
    entrypoint: ["/app/docker-entrypoint.sh"]
    volumes:
      - ./dataanalysis/strage:/tmp/share_file
      - ./dataanalysis/spark/log:/var/log/digdag
    tty: true
    ports:
      - 65432:65432
  metabase:
    image: metabase/metabase:v0.42.3
    ports:
      - 3001:3000
    container_name: metabase_market
  before_db:
    image: mysql:8.0.37-oracle
    container_name: "db_before_market"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketproject
      MYSQL_USER: pythonMySql1
      MYSQL_PASSWORD: pythonMySql1
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - ./dbserver/common/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./dbserver/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
  after_db:
    image: mysql:8.0.37-oracle
    container_name: "db_after_market"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketproject
      MYSQL_USER: pythonMySql1
      MYSQL_PASSWORD: pythonMySql1
      MYSQL_TCP_PORT: 3307
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - ./dbserver/common/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3307:3307
    expose:
      - 3307
    cap_add:
      - SYS_NICE
  digtag_db:
    image: postgres:16-bookworm
    container_name: "db_digtag_market"
    restart: always
    environment:
      POSTGRES_DB: marketproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
