in:
  type: mysql
  host: before_db
  user: pythonMySql1
  password: pythonMySql1
  database: marketproject
  query: |
    select product_id, user_id
    from orders
out:
  type: parquet
  path_prefix: /tmp/share_file/datalake/order_tracker/order_tracker
  compression_codec: GZIP
  overwrite: true
