in:
  type: mysql
  host: before_db
  user: pythonMySql1
  password: pythonMySql1
  database: marketproject
  query: |
    select id, order_id, item_id, quantity, price
    from order_items
out:
  type: parquet
  path_prefix: /tmp/share_file/datalake/order_items/order_items
  compression_codec: GZIP
  overwrite: true
