in:
  type: mysql
  host: before_db
  user: pythonMySql1
  password: pythonMySql1
  database: marketproject
  query: |
    select id, user_id, total_price, status
    from orders
out:
  type: parquet
  path_prefix: /tmp/share_file/datalake/orders/orders
  compression_codec: GZIP
  overwrite: true
